version: '3.8'

services:
  # Elasticsearch - Hybrid Search Engine
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: codeai-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - codeai-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    mem_limit: 4g

  # Redis - Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: codeai-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      - codeai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # PostgreSQL - Metadata Storage
  postgres:
    image: postgres:16-alpine
    container_name: codeai-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-codeai}
      - POSTGRES_USER=${POSTGRES_USER:-codeai}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-codeai_password}
      - POSTGRES_MAX_CONNECTIONS=100
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - codeai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-codeai}"]
      interval: 30s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # MinIO - S3 Compatible Storage
  minio:
    image: minio/minio:latest
    container_name: codeai-minio
    ports:
      - "9000:9000"   # API Port
      - "9001:9001"   # Console Port
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET:-codeai-storage}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - codeai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # Nginx - Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: codeai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - codeai-network
    depends_on:
      - elasticsearch
      - redis
      - postgres
      - minio
    restart: unless-stopped

  # pgAdmin - PostgreSQL Web UI (Optional, for development)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: codeai-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@codeai.local}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - codeai-network
    depends_on:
      - postgres
    profiles:
      - dev
    restart: unless-stopped

  # Redis Commander - Redis Web UI (Optional, for development)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: codeai-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=redis:redis:6379
    networks:
      - codeai-network
    depends_on:
      - redis
    profiles:
      - dev
    restart: unless-stopped

networks:
  codeai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local
  minio-data:
    driver: local
  pgadmin-data:
    driver: local